export const CREATE_POST = 'POST/CREATE_POST';
export const ALL_POSTS = 'POST/ALL_POSTS';
export const DELETE_POSTS = 'POST/DELETE_POSTS';
export const EDIT_POSTS = 'POST/EDIT_POSTS';
export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const REQUEST_POSTS = 'POST/REQUEST_POSTS';
export const CREATE_WAREHOUSE = 'WAREHOUSE/CREATE_WAREHOUSE';
export const ALL_WAREHOUSES = 'WAREHOUSE/ALL_WAREHOUSES';
export const DELETE_WAREHOUSE = 'WAREHOUSE/DELETE_WAREHOUSE';
export const EDIT_WAREHOUSE = 'WAREHOUSE/EDIT_WAREHOUSE';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';



